site_name: Polyhegel Documentation
site_description: Simulator for identifying effective trunk narratives for swarm AI genesis
site_url: https://allenday.github.io/polyhegel/
repo_url: https://github.com/allenday/polyhegel
repo_name: allenday/polyhegel

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            members_order: source
            separate_signature: true
            filters: ["!^_"]
            merge_init_into_class: true
            docstring_section_style: spacy
            show_root_full_path: false
            show_signature_annotations: true
            show_source: false
            heading_level: 1
            parameter_headings: true
            docstring_options:
              ignore_init_summary: true
            selection:
              docstring_style: google
              inherited_members: true
  - autorefs
  - mkdocs-jupyter:
      include_source: True
      ignore_h1_titles: True
      execute: false
      allow_errors: false
      
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ['.']
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - footnotes

nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started.md
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
    - Troubleshooting: getting-started/troubleshooting.md
  - User Guide:
    - Strategic Simulation: guide/simulation.md
    - A2A Agents: guide/a2a-agents.md
    - Strategic Techniques: guide/strategic-techniques.md
    - Tournament Mode: guide/tournament.md
  - Advanced Topics:
    - A2A Agents Deep Dive: a2a-agents.md
    - Security Considerations: security.md
    - Strategic Techniques Reference: strategic_techniques.md
  - API Reference: 
    - Overview: reference/index.md
    - Core Modules: reference/polyhegel/
  - Architecture:
    - Overview: architecture.md
    - System Design: architecture/overview.md
    - Agent System: architecture/agent-system.md
    - Strategic Techniques: architecture/strategic-techniques.md
    - Security: architecture/security.md
    - Core vs Examples: architecture/core-vs-examples.md
    - Technical Domains: architecture/technical-architecture-domain.md
  - Development:
    - Extending Polyhegel: development/extending-polyhegel.md
  - Contributing:
    - Development Guide: contributing/development.md
    - Testing: contributing/testing.md
    - Release Process: contributing/releases.md
    - Documentation Strategy: documentation_strategy.md
    - Docstring Prioritization: docstring_prioritization.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/allenday/polyhegel
  version:
    provider: mike
  analytics:
    provider: google
    property: G-XXXXXXXXXX  # Replace with actual tracking ID