name: Build Documentation

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy to GitHub Pages'
        required: false
        default: false
        type: boolean
  push:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'polyhegel/**/*.py'
    branches:
      - dev
      - main

env:
  PYTHONPATH: ${{ github.workspace }}

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    
    - name: Build documentation
      run: make docs
    
    - name: Upload docs artifact
      uses: actions/upload-artifact@v4
      with:
        name: documentation-site
        path: site/
        retention-days: 30
    
    - name: Deploy to GitHub Pages
      if: ${{ github.ref == 'refs/heads/main' || inputs.deploy == true }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        cname: polyhegel.postfiat.org  # Optional: if you have a custom domain

  test-docs:
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
    - name: Download docs artifact
      uses: actions/download-artifact@v4
      with:
        name: documentation-site
        path: site/
    
    - name: Debug artifact contents
      run: |
        echo "=== Artifact contents ==="
        find site/ -type f -name "*.html" | head -20
        echo "=== Getting started directory ==="
        ls -la site/getting-started/ || echo "getting-started directory not found"
        echo "=========================="
    
    - name: Test documentation structure
      run: |
        echo "Testing documentation build..."
        test -f site/index.html || (echo "Missing index.html" && exit 1)
        test -d site/reference || (echo "Missing API reference" && exit 1)
        test -f site/getting-started/installation.html || (echo "Missing installation guide" && exit 1)
        test -f site/getting-started/quickstart.html || (echo "Missing quickstart guide" && exit 1)
        echo "✅ Documentation structure validated"
    
    - name: Check for broken links (basic)
      run: |
        echo "Checking for common issues..."
        if grep -r "404\|Not Found\|ERROR" site/ --include="*.html"; then
          echo "⚠️  Found potential issues in documentation"
        else
          echo "✅ No obvious issues found"
        fi